### ISSUE TITLE
May I ask when this project will be open-sourced?

### ISSUE THREAD

**Issue by Seperendity** [YulongBonjour/STTM#1]
Nice work! I hope study it as soon as possible.

**Comment by YulongBonjour** [comment]
Yes. I will release my code and the pre-trained model weights in April.

**Comment by Seperendity** [comment]
That's fantastic, thank you again for your excellent work.

**Comment by Seperendity** [comment]
> Yes. I will release my code and the pre-trained model weights in April.

hello, will the code be released in the future?
